// Purpose: Salary TDS compliance built from the payroll snapshots — the monthly TDS statement (what must be
//   deposited, and whether it was), the quarterly TDS return data (Form 138; Form 24Q before 1-Apr-2026) with its
//   deductee-wise Annexure I and the annual salary Annexure II, challan and statement-receipt records, and the
//   per-employee Form 130 (Form 16 before 1-Apr-2026) data.
// Responsibilities: Reads finalized PayrollRun rows (including final settlements) and never recomputes tax; owns
//   TdsChallan / TdsStatement CRUD.
// Important: These are working papers prepared from payroll. The return itself must still be validated and filed
//   through the government's utility, and the certificate that is legally valid is the one generated by TRACES
//   from the filed return.
import {
  BadRequestException,
  ForbiddenException,
  Inject,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import {
  AuditModule,
  PayrollRunStatus,
  Role,
  type TdsStatement,
} from '@prisma/client';
import { PRISMA_CLIENT } from '../prisma/prisma.module';
import type { ExtendedPrismaClient } from '../prisma/prisma.module';
import { AuditLogService } from '../audit-log/audit-log.service';
import { SALARY_COMPONENT_CODES } from '../common/reserved-codes';
import type { ReportPayload } from '../reports/reports.service';
import type { ReportColumn } from '../reports/report-export';
import {
  CreateChallanDto,
  SetStatementDto,
  UpdateChallanDto,
} from './dto/tds.dto';
import {
  PAN_PATTERN,
  TdsQuarter,
  challanDueDate,
  isValidTaxYear,
  monthsOfQuarter,
  quarterOf,
  splitMonthlyTds,
  statementDueDate,
  taxYearOf,
} from './tds-math';

interface Actor {
  id: string;
  role: Role;
}

interface Line {
  code: string;
  amount: number;
}

interface TaxDetailsShape {
  regime?: string;
  grossAnnualIncome?: number;
  exemptions?: { hra?: number; lta?: number };
  deductions?: Record<string, number>;
  taxableIncome?: number;
  taxBeforeCess?: number;
  rebate?: number;
  surcharge?: number;
  cess?: number;
  totalAnnualTax?: number;
  relief89?: number;
  ytdTDS?: number;
  previousEmployerTDS?: number;
}

// A run counts for TDS once payroll has approved it (settlements go straight to APPROVED).
const PAID_OUT: PayrollRunStatus[] = [
  PayrollRunStatus.APPROVED,
  PayrollRunStatus.LOCKED,
  PayrollRunStatus.PAID,
];

const MONTH_NAMES = [
  '',
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

const pad = (n: number) => String(n).padStart(2, '0');
const isoDate = (d: Date | null | undefined): string | null =>
  d ? d.toISOString().slice(0, 10) : null;
const tdsOf = (deductions: unknown): number =>
  ((deductions as Line[] | null) ?? []).find(
    (l) => l.code === SALARY_COMPONENT_CODES.INCOME_TAX,
  )?.amount ?? 0;
const todayStr = () => new Date().toISOString().slice(0, 10);

export interface DeducteeRow {
  employeeId: string;
  employeeCode: string;
  name: string;
  pan: string;
  panValid: boolean;
  month: number;
  year: number;
  paymentDate: string;
  amountPaid: number;
  tds: number;
  tax: number;
  surcharge: number;
  cess: number;
  isFinalSettlement: boolean;
}

@Injectable()
export class TdsComplianceService {
  constructor(
    @Inject(PRISMA_CLIENT) private readonly scopedPrisma: ExtendedPrismaClient,
    private readonly auditLogService: AuditLogService,
  ) {}

  private assertTaxYear(taxYear: string) {
    if (!isValidTaxYear(taxYear)) {
      throw new BadRequestException(
        'financialYear must look like 2026-27 (consecutive years).',
      );
    }
  }

  // Decrypted personalData per employee. Identifiers are encrypted at rest and only the top-level tenant-scoped
  // read decrypts them — a nested `include` returns the raw "enc:v1:..." ciphertext, which must never reach a
  // certificate or a return.
  private async personalDataById(
    organizationId: string,
    employeeIds: string[],
  ): Promise<Map<string, Record<string, unknown>>> {
    const ids = [...new Set(employeeIds)];
    if (ids.length === 0) return new Map();
    const users = await this.scopedPrisma.user.findMany({
      where: { organizationId, id: { in: ids } },
      select: { id: true, personalData: true },
    });
    return new Map(
      users.map((u) => [
        u.id,
        (u.personalData ?? {}) as Record<string, unknown>,
      ]),
    );
  }

  // ── Deductee rows ────────────────────────────────────────────────────────

  private async deducteeRows(
    organizationId: string,
    month: number,
    year: number,
  ): Promise<DeducteeRow[]> {
    const runs = await this.scopedPrisma.payrollRun.findMany({
      where: { organizationId, month, year, status: { in: PAID_OUT } },
      include: {
        employee: {
          select: {
            id: true,
            name: true,
            employeeId: true,
            personalData: true,
          },
        },
      },
      orderBy: [
        { employee: { employeeId: 'asc' } },
        { isFinalSettlement: 'asc' },
      ],
    });
    const pdById = await this.personalDataById(
      organizationId,
      runs.map((r) => r.employeeId),
    );
    return runs
      .filter(
        (r) =>
          (r.taxableGross ?? r.grossSalary) > 0 || tdsOf(r.deductions) !== 0,
      )
      .map((r) => {
        const pd = pdById.get(r.employeeId) ?? {};
        const pan =
          typeof pd.panNumber === 'string'
            ? pd.panNumber.trim().toUpperCase()
            : '';
        const td = r.taxDetails as TaxDetailsShape | null;
        const tds = tdsOf(r.deductions);
        const annualTax = td?.totalAnnualTax ?? 0;
        const split = splitMonthlyTds(
          tds,
          td
            ? {
                taxAfterRebate: Math.max(
                  0,
                  annualTax - (td.surcharge ?? 0) - (td.cess ?? 0),
                ),
                surcharge: td.surcharge ?? 0,
                cess: td.cess ?? 0,
              }
            : null,
        );
        return {
          employeeId: r.employee.id,
          employeeCode: r.employee.employeeId,
          name: r.employee.name,
          pan: pan || '-',
          panValid: PAN_PATTERN.test(pan),
          month,
          year,
          paymentDate:
            isoDate(r.paidAt) ??
            isoDate(r.lockedAt) ??
            isoDate(r.approvedAt) ??
            `${year}-${pad(month)}-${pad(new Date(Date.UTC(year, month, 0)).getUTCDate())}`,
          amountPaid: r.taxableGross ?? r.grossSalary,
          tds,
          tax: split.tax,
          surcharge: split.surcharge,
          cess: split.cess,
          isFinalSettlement: r.isFinalSettlement,
        };
      });
  }

  // ── Monthly TDS statement ───────────────────────────────────────────────

  async monthlySummary(month: number, year: number, organizationId: string) {
    const rows = await this.deducteeRows(organizationId, month, year);
    const challans = await this.scopedPrisma.tdsChallan.findMany({
      where: { organizationId, month, year },
      orderBy: [{ depositDate: 'asc' }, { createdAt: 'asc' }],
    });
    const totalTds = rows.reduce((s, r) => s + r.tds, 0);
    const deposited = challans.reduce((s, c) => s + c.tdsAmount, 0);
    const dueDate = challanDueDate(month, year);
    const lateChallans = challans.filter((c) => c.depositDate > dueDate);
    const shortfall = Math.max(0, totalTds - deposited);
    let status:
      'NO_TDS' | 'PENDING' | 'OVERDUE' | 'PARTIAL' | 'DEPOSITED' | 'EXCESS';
    if (totalTds === 0 && deposited === 0) status = 'NO_TDS';
    else if (deposited > totalTds) status = 'EXCESS';
    else if (deposited >= totalTds) status = 'DEPOSITED';
    else if (todayStr() > dueDate) status = 'OVERDUE';
    else status = deposited > 0 ? 'PARTIAL' : 'PENDING';
    return {
      month,
      year,
      monthLabel: `${MONTH_NAMES[month]} ${year}`,
      financialYear: taxYearOf(month, year),
      quarter: quarterOf(month),
      dueDate,
      status,
      employees: rows.length,
      totalAmountPaid: rows.reduce((s, r) => s + r.amountPaid, 0),
      totalTds,
      deposited,
      shortfall,
      lateDepositCount: lateChallans.length,
      rows,
      challans,
    };
  }

  async monthlyReport(
    month: number,
    year: number,
    organizationId: string,
  ): Promise<ReportPayload> {
    const s = await this.monthlySummary(month, year, organizationId);
    const challanText = s.challans.length
      ? s.challans
          .map(
            (c) =>
              `BSR ${c.bsrCode} / Serial ${c.challanSerialNo} / ${c.depositDate} / ${c.tdsAmount}`,
          )
          .join('; ')
      : 'No challan recorded';
    return {
      title: `Monthly TDS Statement — ${s.monthLabel}`,
      subtitle: `Due ${s.dueDate} | TDS deducted ${s.totalTds} | Deposited ${s.deposited} | Shortfall ${s.shortfall} | ${challanText}`,
      columns: this.deducteeColumns(),
      rows: s.rows.map((r) => this.deducteeReportRow(r)),
      filename: `tds_monthly_${year}_${pad(month)}`,
    };
  }

  private deducteeColumns(): ReportColumn[] {
    return [
      { header: 'Employee ID', key: 'employeeCode', width: 14 },
      { header: 'Name', key: 'name', width: 22 },
      { header: 'PAN', key: 'pan', width: 14 },
      { header: 'Month', key: 'monthLabel', width: 16 },
      { header: 'Date of Payment / Credit', key: 'paymentDate', width: 18 },
      { header: 'Amount Paid / Credited', key: 'amountPaid', width: 18 },
      { header: 'Income Tax', key: 'tax', width: 12 },
      { header: 'Surcharge', key: 'surcharge', width: 12 },
      { header: 'Cess', key: 'cess', width: 10 },
      { header: 'Total TDS Deducted', key: 'tds', width: 16 },
      { header: 'Final Settlement', key: 'fnf', width: 14 },
      { header: 'PAN Check', key: 'panCheck', width: 14 },
    ];
  }

  private deducteeReportRow(r: DeducteeRow): Record<string, unknown> {
    return {
      employeeCode: r.employeeCode,
      name: r.name,
      pan: r.pan,
      monthLabel: `${MONTH_NAMES[r.month]} ${r.year}`,
      paymentDate: r.paymentDate,
      amountPaid: r.amountPaid,
      tax: r.tax,
      surcharge: r.surcharge,
      cess: r.cess,
      tds: r.tds,
      fnf: r.isFinalSettlement ? 'Yes' : 'No',
      panCheck: r.panValid ? 'OK' : r.pan === '-' ? 'MISSING' : 'INVALID',
    };
  }

  // ── Quarterly return (Form 138 data) ────────────────────────────────────

  async quarterlySummary(
    taxYear: string,
    quarter: number,
    organizationId: string,
  ) {
    this.assertTaxYear(taxYear);
    const q = quarter as TdsQuarter;
    const months = monthsOfQuarter(taxYear, q);
    const monthly: Awaited<
      ReturnType<TdsComplianceService['monthlySummary']>
    >[] = [];
    for (const m of months) {
      monthly.push(await this.monthlySummary(m.month, m.year, organizationId));
    }
    const statement = await this.scopedPrisma.tdsStatement.findFirst({
      where: { organizationId, financialYear: taxYear, quarter },
    });
    const rows = monthly.flatMap((m) => m.rows);
    const totalTds = monthly.reduce((s, m) => s + m.totalTds, 0);
    const deposited = monthly.reduce((s, m) => s + m.deposited, 0);

    // Things that will make the return fail validation or the figures disagree — shown before anyone files.
    const checks: { level: 'error' | 'warning'; message: string }[] = [];
    const missingPan = rows.filter((r) => r.pan === '-' && r.tds > 0);
    const invalidPan = rows.filter((r) => r.pan !== '-' && !r.panValid);
    if (missingPan.length)
      checks.push({
        level: 'error',
        message: `${missingPan.length} deductee(s) with TDS have no PAN: ${[...new Set(missingPan.map((r) => r.name))].slice(0, 5).join(', ')}.`,
      });
    if (invalidPan.length)
      checks.push({
        level: 'error',
        message: `${invalidPan.length} deductee row(s) have an invalid PAN format.`,
      });
    for (const m of monthly) {
      if (m.totalTds > 0 && m.challans.length === 0)
        checks.push({
          level: 'error',
          message: `${m.monthLabel}: TDS of ${m.totalTds} deducted but no challan recorded (due ${m.dueDate}).`,
        });
      else if (m.shortfall > 0)
        checks.push({
          level: 'error',
          message: `${m.monthLabel}: deposited ${m.deposited} is ${m.shortfall} short of ${m.totalTds} deducted.`,
        });
      else if (m.status === 'EXCESS')
        checks.push({
          level: 'warning',
          message: `${m.monthLabel}: deposited ${m.deposited} exceeds TDS deducted ${m.totalTds}.`,
        });
      if (m.lateDepositCount > 0)
        checks.push({
          level: 'warning',
          message: `${m.monthLabel}: ${m.lateDepositCount} challan(s) deposited after the due date ${m.dueDate} — interest u/s 201(1A) may apply.`,
        });
    }
    if (!statement)
      checks.push({
        level: 'warning',
        message: `No acknowledgement number recorded yet for this quarter's statement (due ${statementDueDate(taxYear, q)}).`,
      });
    return {
      financialYear: taxYear,
      quarter,
      form: Number(taxYear.slice(0, 4)) >= 2026 ? '138' : '24Q',
      statementDueDate: statementDueDate(taxYear, q),
      statement,
      employees: new Set(rows.map((r) => r.employeeId)).size,
      totalAmountPaid: rows.reduce((s, r) => s + r.amountPaid, 0),
      totalTds,
      deposited,
      months: monthly.map((m) => ({
        month: m.month,
        year: m.year,
        monthLabel: m.monthLabel,
        dueDate: m.dueDate,
        status: m.status,
        totalTds: m.totalTds,
        deposited: m.deposited,
        shortfall: m.shortfall,
        challans: m.challans,
      })),
      checks,
      ready: checks.every((c) => c.level !== 'error'),
      rows,
    };
  }

  // Annexure I — deductee-wise, one row per deduction with the challan(s) it is deposited against.
  async quarterlyReport(
    taxYear: string,
    quarter: number,
    organizationId: string,
  ): Promise<ReportPayload> {
    const s = await this.quarterlySummary(taxYear, quarter, organizationId);
    const org = await this.scopedPrisma.organization.findFirst({
      where: { id: organizationId },
      select: { tan: true, pan: true },
    });
    const challansByMonth = new Map(
      s.months.map((m) => [
        `${m.year}-${m.month}`,
        m.challans
          .map((c) => `${c.bsrCode}/${c.challanSerialNo}/${c.depositDate}`)
          .join(' ; ') || '-',
      ]),
    );
    const columns: ReportColumn[] = [
      ...this.deducteeColumns().filter((c) => c.key !== 'panCheck'),
      { header: 'TDS Deposited', key: 'deposited', width: 14 },
      { header: 'Challan (BSR/Serial/Date)', key: 'challan', width: 40 },
      { header: 'PAN Check', key: 'panCheck', width: 14 },
    ];
    // Deposited per deductee: the month's challans cover the month's deductions pro rata.
    const monthDeposit = new Map(
      s.months.map((m) => [
        `${m.year}-${m.month}`,
        m.totalTds > 0 ? Math.min(1, m.deposited / m.totalTds) : 0,
      ]),
    );
    return {
      title: `Quarterly TDS Return (Form ${s.form}) Annexure I — Q${quarter} FY ${taxYear}`,
      subtitle: `Deductor TAN: ${org?.tan || 'not set'} | PAN: ${org?.pan || 'not set'} | Statement due ${s.statementDueDate}${s.statement ? ` | Receipt ${s.statement.receiptNumber}` : ''}`,
      columns,
      rows: s.rows.map((r) => ({
        ...this.deducteeReportRow(r),
        deposited: Math.round(
          r.tds * (monthDeposit.get(`${r.year}-${r.month}`) ?? 0),
        ),
        challan: challansByMonth.get(`${r.year}-${r.month}`) ?? '-',
      })),
      filename: `tds_return_q${quarter}_${taxYear}`,
    };
  }

  // ── Annual salary details (Annexure II / Form 130 Annexure I basis) ─────

  private async annualRuns(
    organizationId: string,
    taxYear: string,
    employeeId?: string,
  ) {
    const startYear = Number(taxYear.slice(0, 4));
    return this.scopedPrisma.payrollRun.findMany({
      where: {
        organizationId,
        status: { in: PAID_OUT },
        ...(employeeId ? { employeeId } : {}),
        OR: [
          { financialYear: taxYear },
          // Rows saved without a label (older settlements): place them by calendar.
          {
            financialYear: null,
            OR: [
              { year: startYear, month: { gte: 4 } },
              { year: startYear + 1, month: { lte: 3 } },
            ],
          },
        ],
      },
      include: {
        employee: {
          select: {
            id: true,
            name: true,
            employeeId: true,
            designation: true,
            joiningDate: true,
            personalData: true,
          },
        },
      },
      // A final settlement is the employee's last word for its month: it sorts after the regular run so its
      // tax computation (income actually earned to the exit) is the one Form 130 reports.
      orderBy: [
        { year: 'asc' },
        { month: 'asc' },
        { isFinalSettlement: 'asc' },
      ],
    });
  }

  private annualFromRuns(
    runs: Awaited<ReturnType<TdsComplianceService['annualRuns']>>,
  ) {
    const byEmp = new Map<
      string,
      {
        employee: (typeof runs)[number]['employee'];
        gross: number;
        taxableSalary: number;
        tds: number;
        first: { month: number; year: number };
        last: { month: number; year: number };
        details: TaxDetailsShape | null;
        runs: typeof runs;
      }
    >();
    for (const r of runs) {
      const cur = byEmp.get(r.employeeId) ?? {
        employee: r.employee,
        gross: 0,
        taxableSalary: 0,
        tds: 0,
        first: { month: r.month, year: r.year },
        last: { month: r.month, year: r.year },
        details: null,
        runs: [] as typeof runs,
      };
      cur.gross += r.grossSalary;
      cur.taxableSalary += r.taxableGross ?? r.grossSalary;
      cur.tds += tdsOf(r.deductions);
      cur.last = { month: r.month, year: r.year };
      if (r.taxDetails) cur.details = r.taxDetails as TaxDetailsShape;
      cur.runs.push(r);
      byEmp.set(r.employeeId, cur);
    }
    return [...byEmp.values()];
  }

  async annexureIIReport(
    taxYear: string,
    organizationId: string,
  ): Promise<ReportPayload> {
    this.assertTaxYear(taxYear);
    const people = this.annualFromRuns(
      await this.annualRuns(organizationId, taxYear),
    );
    const sumDed = (d: TaxDetailsShape | null) =>
      Object.entries(d?.deductions ?? {})
        .filter(([k]) => k !== 'standard')
        .reduce((s, [, v]) => s + (v || 0), 0);
    const columns: ReportColumn[] = [
      { header: 'Employee ID', key: 'code', width: 14 },
      { header: 'Name', key: 'name', width: 22 },
      { header: 'PAN', key: 'pan', width: 14 },
      { header: 'Regime', key: 'regime', width: 10 },
      { header: 'Period From', key: 'from', width: 12 },
      { header: 'Period To', key: 'to', width: 12 },
      { header: 'Gross Salary', key: 'gross', width: 14 },
      { header: 'Taxable Salary', key: 'taxableSalary', width: 14 },
      { header: 'Exemptions (HRA/LTA)', key: 'exemptions', width: 16 },
      { header: 'Standard Deduction', key: 'standard', width: 16 },
      {
        header: 'Chapter VI-A / Other Deductions',
        key: 'chapter6a',
        width: 20,
      },
      { header: 'Total Income', key: 'income', width: 14 },
      { header: 'Tax on Income', key: 'taxBeforeCess', width: 14 },
      { header: 'Rebate 87A', key: 'rebate', width: 12 },
      { header: 'Surcharge', key: 'surcharge', width: 12 },
      { header: 'Cess', key: 'cess', width: 10 },
      { header: 'Net Tax Payable', key: 'annualTax', width: 14 },
      { header: 'Previous Employer TDS', key: 'prevTds', width: 16 },
      { header: 'TDS Deducted', key: 'tds', width: 14 },
    ];
    const pdById = await this.personalDataById(
      organizationId,
      people.map((p) => p.employee.id),
    );
    const rows = people.map((p) => {
      const d = p.details;
      const pd = pdById.get(p.employee.id) ?? {};
      return {
        code: p.employee.employeeId,
        name: p.employee.name,
        pan:
          typeof pd.panNumber === 'string' && pd.panNumber ? pd.panNumber : '-',
        regime: d?.regime ?? '-',
        from: `${pad(p.first.month)}/${p.first.year}`,
        to: `${pad(p.last.month)}/${p.last.year}`,
        gross: p.gross,
        taxableSalary: p.taxableSalary,
        exemptions: (d?.exemptions?.hra ?? 0) + (d?.exemptions?.lta ?? 0),
        standard: d?.deductions?.standard ?? 0,
        chapter6a: sumDed(d),
        income: d?.taxableIncome ?? 0,
        taxBeforeCess: d?.taxBeforeCess ?? 0,
        rebate: d?.rebate ?? 0,
        surcharge: d?.surcharge ?? 0,
        cess: d?.cess ?? 0,
        annualTax: d?.totalAnnualTax ?? 0,
        prevTds: d?.previousEmployerTDS ?? 0,
        tds: p.tds,
      };
    });
    return {
      title: `Annual Salary Details (Annexure II) — FY ${taxYear}`,
      subtitle:
        "Reported with the last quarter's statement. Figures are the employee's final computed position in payroll.",
      columns,
      rows,
      filename: `tds_annexure_ii_${taxYear}`,
    };
  }

  // ── Challans ────────────────────────────────────────────────────────────

  listChallans(taxYear: string, organizationId: string) {
    this.assertTaxYear(taxYear);
    return this.scopedPrisma.tdsChallan.findMany({
      where: { organizationId, financialYear: taxYear },
      orderBy: [{ year: 'asc' }, { month: 'asc' }, { depositDate: 'asc' }],
    });
  }

  async createChallan(
    dto: CreateChallanDto,
    actor: Actor,
    organizationId: string,
  ) {
    if (dto.depositDate < `${dto.year}-${pad(dto.month)}-01`) {
      throw new BadRequestException(
        'The deposit date cannot be before the month the tax was deducted in.',
      );
    }
    const dup = await this.scopedPrisma.tdsChallan.findFirst({
      where: {
        organizationId,
        bsrCode: dto.bsrCode,
        challanSerialNo: dto.challanSerialNo,
        depositDate: dto.depositDate,
      },
    });
    if (dup) {
      throw new BadRequestException(
        'A challan with this BSR code, serial number and deposit date is already recorded.',
      );
    }
    const created = await this.scopedPrisma.tdsChallan.create({
      data: {
        organizationId,
        month: dto.month,
        year: dto.year,
        financialYear: taxYearOf(dto.month, dto.year),
        quarter: quarterOf(dto.month),
        bsrCode: dto.bsrCode,
        challanSerialNo: dto.challanSerialNo,
        depositDate: dto.depositDate,
        tdsAmount: dto.tdsAmount,
        interest: dto.interest ?? 0,
        fee: dto.fee ?? 0,
        notes: dto.notes ?? '',
        createdById: actor.id,
      },
    });
    await this.auditLogService.log({
      actorId: actor.id,
      action: 'TDS_CHALLAN_ADDED',
      module: AuditModule.PAYROLL,
      organizationId,
      targetId: created.id,
      details: {
        month: dto.month,
        year: dto.year,
        bsrCode: dto.bsrCode,
        challanSerialNo: dto.challanSerialNo,
        tdsAmount: dto.tdsAmount,
      },
    });
    return created;
  }

  async updateChallan(
    id: string,
    dto: UpdateChallanDto,
    actor: Actor,
    organizationId: string,
  ) {
    const before = await this.scopedPrisma.tdsChallan.findFirst({
      where: { id, organizationId },
    });
    if (!before) throw new NotFoundException('Challan not found.');
    if (
      dto.depositDate &&
      dto.depositDate < `${before.year}-${pad(before.month)}-01`
    ) {
      throw new BadRequestException(
        'The deposit date cannot be before the month the tax was deducted in.',
      );
    }
    await this.scopedPrisma.tdsChallan.updateMany({
      where: { id, organizationId },
      data: { ...dto },
    });
    const after = await this.scopedPrisma.tdsChallan.findFirstOrThrow({
      where: { id, organizationId },
    });
    await this.auditLogService.log({
      actorId: actor.id,
      action: 'TDS_CHALLAN_UPDATED',
      module: AuditModule.PAYROLL,
      organizationId,
      targetId: id,
      details: {
        before: {
          bsrCode: before.bsrCode,
          challanSerialNo: before.challanSerialNo,
          depositDate: before.depositDate,
          tdsAmount: before.tdsAmount,
        },
        after: {
          bsrCode: after.bsrCode,
          challanSerialNo: after.challanSerialNo,
          depositDate: after.depositDate,
          tdsAmount: after.tdsAmount,
        },
      },
    });
    return after;
  }

  async removeChallan(id: string, actor: Actor, organizationId: string) {
    const row = await this.scopedPrisma.tdsChallan.findFirst({
      where: { id, organizationId },
    });
    if (!row) throw new NotFoundException('Challan not found.');
    const filed = await this.scopedPrisma.tdsStatement.findFirst({
      where: {
        organizationId,
        financialYear: row.financialYear,
        quarter: row.quarter,
      },
    });
    if (filed) {
      throw new BadRequestException(
        `The Q${row.quarter} statement for FY ${row.financialYear} is already filed (receipt ${filed.receiptNumber}) — a challan it reports can no longer be removed.`,
      );
    }
    await this.scopedPrisma.tdsChallan.deleteMany({
      where: { id, organizationId },
    });
    await this.auditLogService.log({
      actorId: actor.id,
      action: 'TDS_CHALLAN_REMOVED',
      module: AuditModule.PAYROLL,
      organizationId,
      targetId: id,
      details: {
        month: row.month,
        year: row.year,
        bsrCode: row.bsrCode,
        challanSerialNo: row.challanSerialNo,
        tdsAmount: row.tdsAmount,
      },
    });
    return { deleted: true };
  }

  // ── Statement receipts ──────────────────────────────────────────────────

  listStatements(taxYear: string, organizationId: string) {
    this.assertTaxYear(taxYear);
    return this.scopedPrisma.tdsStatement.findMany({
      where: { organizationId, financialYear: taxYear },
      orderBy: { quarter: 'asc' },
    });
  }

  async setStatement(
    dto: SetStatementDto,
    actor: Actor,
    organizationId: string,
  ) {
    this.assertTaxYear(dto.financialYear);
    const existing = await this.scopedPrisma.tdsStatement.findFirst({
      where: {
        organizationId,
        financialYear: dto.financialYear,
        quarter: dto.quarter,
      },
    });
    const data = {
      formType:
        dto.formType ??
        (Number(dto.financialYear.slice(0, 4)) >= 2026 ? '138' : '24Q'),
      receiptNumber: dto.receiptNumber.toUpperCase(),
      filedOn: dto.filedOn ?? null,
    };
    let row: TdsStatement;
    if (existing) {
      await this.scopedPrisma.tdsStatement.updateMany({
        where: { id: existing.id, organizationId },
        data,
      });
      row = await this.scopedPrisma.tdsStatement.findFirstOrThrow({
        where: { id: existing.id, organizationId },
      });
    } else {
      row = await this.scopedPrisma.tdsStatement.create({
        data: {
          organizationId,
          financialYear: dto.financialYear,
          quarter: dto.quarter,
          createdById: actor.id,
          ...data,
        },
      });
    }
    await this.auditLogService.log({
      actorId: actor.id,
      action: 'TDS_STATEMENT_SET',
      module: AuditModule.PAYROLL,
      organizationId,
      targetId: row.id,
      details: {
        financialYear: dto.financialYear,
        quarter: dto.quarter,
        receiptNumber: data.receiptNumber,
        previous: existing?.receiptNumber ?? null,
      },
    });
    return row;
  }

  // ── Form 130 ────────────────────────────────────────────────────────────

  async form130Data(
    employeeId: string,
    taxYear: string,
    actor: Actor,
    organizationId: string,
  ) {
    this.assertTaxYear(taxYear);
    const isHr = actor.role === Role.ADMIN || actor.role === Role.HR;
    const runs = await this.annualRuns(organizationId, taxYear, employeeId);
    if (runs.length === 0) {
      throw new NotFoundException(
        `No finalized payroll found for this employee in FY ${taxYear}.`,
      );
    }
    const statements = await this.scopedPrisma.tdsStatement.findMany({
      where: { organizationId, financialYear: taxYear },
    });
    // An employee only gets the certificate once the year's last statement is on record; HR can always prepare it.
    if (!isHr && !statements.some((s) => s.quarter === 4)) {
      throw new ForbiddenException(
        `Your Form 130 for FY ${taxYear} is not available yet — it is issued after the year's TDS statements are filed.`,
      );
    }
    const person = this.annualFromRuns(runs)[0];
    const org = await this.scopedPrisma.organization.findFirst({
      where: { id: organizationId },
      select: {
        companyName: true,
        legalName: true,
        tan: true,
        pan: true,
        registeredAddress: true,
        corporateAddress: true,
        contactEmail: true,
        phone: true,
      },
    });
    const challans = await this.scopedPrisma.tdsChallan.findMany({
      where: { organizationId, financialYear: taxYear },
    });
    const pd =
      (await this.personalDataById(organizationId, [employeeId])).get(
        employeeId,
      ) ?? {};
    const startYear = Number(taxYear.slice(0, 4));
    const orgRuns = await this.scopedPrisma.payrollRun.findMany({
      where: {
        organizationId,
        status: { in: PAID_OUT },
        OR: [
          { year: startYear, month: { gte: 4 } },
          { year: startYear + 1, month: { lte: 3 } },
        ],
      },
      select: { month: true, year: true, deductions: true },
    });
    const orgMonthTds = new Map<string, number>();
    for (const r of orgRuns) {
      const k = `${r.year}-${r.month}`;
      orgMonthTds.set(k, (orgMonthTds.get(k) ?? 0) + tdsOf(r.deductions));
    }
    const quarters = ([1, 2, 3, 4] as TdsQuarter[]).map((q) => {
      const ms = monthsOfQuarter(taxYear, q);
      let amountPaid = 0,
        tdsDeducted = 0,
        tdsDeposited = 0;
      for (const m of ms) {
        const mRuns = runs.filter(
          (r) => r.month === m.month && r.year === m.year,
        );
        const empTds = mRuns.reduce((s, r) => s + tdsOf(r.deductions), 0);
        amountPaid += mRuns.reduce(
          (s, r) => s + (r.taxableGross ?? r.grossSalary),
          0,
        );
        tdsDeducted += empTds;
        // Org-wide challans for the month cover that month's deductions pro rata.
        const monthTotal = orgMonthTds.get(`${m.year}-${m.month}`) ?? 0;
        const dep = challans
          .filter((c) => c.month === m.month && c.year === m.year)
          .reduce((s, c) => s + c.tdsAmount, 0);
        tdsDeposited +=
          monthTotal > 0
            ? Math.round(empTds * Math.min(1, dep / monthTotal))
            : 0;
      }
      const st = statements.find((s) => s.quarter === q);
      return {
        quarter: q,
        receiptNumber: st?.receiptNumber ?? null,
        formType: st?.formType ?? null,
        amountPaid,
        tdsDeducted,
        tdsDeposited,
      };
    });
    const d = person.details;
    const deductions = d?.deductions ?? {};
    const chapter6a = Object.entries(deductions).filter(
      ([k]) => k !== 'standard',
    );
    return {
      financialYear: taxYear,
      formName: Number(taxYear.slice(0, 4)) >= 2026 ? 'Form 130' : 'Form 16',
      employer: {
        name: org?.legalName || org?.companyName || '-',
        address: org?.registeredAddress || org?.corporateAddress || '-',
        pan: org?.pan || '-',
        tan: org?.tan || '-',
        email: org?.contactEmail || '-',
        phone: org?.phone || '-',
      },
      employee: {
        name: person.employee.name,
        code: person.employee.employeeId,
        designation: person.employee.designation,
        pan:
          typeof pd.panNumber === 'string' && pd.panNumber ? pd.panNumber : '-',
        address:
          typeof pd.currentAddress === 'string' && pd.currentAddress
            ? pd.currentAddress
            : '-',
      },
      period: {
        from: `${person.first.year}-${pad(person.first.month)}-01`,
        to: `${person.last.year}-${pad(person.last.month)}-${pad(new Date(Date.UTC(person.last.year, person.last.month, 0)).getUTCDate())}`,
      },
      quarters,
      totals: {
        amountPaid: quarters.reduce((s, q) => s + q.amountPaid, 0),
        tdsDeducted: quarters.reduce((s, q) => s + q.tdsDeducted, 0),
        tdsDeposited: quarters.reduce((s, q) => s + q.tdsDeposited, 0),
      },
      annexure: {
        regime: d?.regime ?? '-',
        grossSalary: person.gross,
        taxableSalary: person.taxableSalary,
        grossTotalIncome: d?.grossAnnualIncome ?? person.taxableSalary,
        exemptionHra: d?.exemptions?.hra ?? 0,
        exemptionLta: d?.exemptions?.lta ?? 0,
        standardDeduction: deductions.standard ?? 0,
        chapter6a: chapter6a
          .map(([k, v]) => ({ section: k, amount: v }))
          .filter((x) => x.amount > 0),
        totalIncome: d?.taxableIncome ?? 0,
        taxOnIncome: d?.taxBeforeCess ?? 0,
        rebate: d?.rebate ?? 0,
        surcharge: d?.surcharge ?? 0,
        cess: d?.cess ?? 0,
        relief89: d?.relief89 ?? 0,
        netTaxPayable: d?.totalAnnualTax ?? 0,
        previousEmployerTds: d?.previousEmployerTDS ?? 0,
        tdsDeducted: person.tds,
        balance:
          (d?.totalAnnualTax ?? 0) - (d?.previousEmployerTDS ?? 0) - person.tds,
      },
      issuedAt: new Date().toISOString().slice(0, 10),
      traces: statements.some((s) => s.quarter === 4),
    };
  }
}
