-- AlterTable: adds Document Numbering entries for the 10 new letter types
-- (Confirmation/Probation Extension/Promotion/Increment/Transfer/
-- Resignation Acceptance/Termination/Warning Letters, NDA, Non-Compete
-- Agreement) — see letter-template-defaults.ts. issueDocumentNumber()
-- already self-heals a missing key via its own defaultEntry() fallback,
-- so this isn't strictly required for correctness, but gives every org
-- (existing and new) the same polished label/format the other 7 letter
-- types have from day one instead of a generic "CONFIRMATIONLETTER-{0001}"
-- fallback on first use.
ALTER TABLE "organizations"
  ALTER COLUMN "documentNumbering" SET DEFAULT '{"employeeId":{"label":"Employee ID","format":"DP-{00000}","resetRule":"never","counter":0,"lastPeriodKey":null},"payslip":{"label":"Payslip","format":"PS-{DD_MM_YYYY}-{00001}","resetRule":"monthly","counter":0,"lastPeriodKey":null},"offerLetter":{"label":"Offer Letter","format":"OL-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"appointmentLetter":{"label":"Appointment Letter","format":"AL-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"experienceLetter":{"label":"Experience Letter","format":"EL-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"relievingLetter":{"label":"Relieving Letter","format":"RL-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"salaryCertificate":{"label":"Salary Certificate","format":"SC-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"fullFinalSettlement":{"label":"Full & Final Settlement","format":"FNF-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"experienceCertificate":{"label":"Experience Certificate","format":"EC-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"confirmationLetter":{"label":"Confirmation Letter","format":"CL-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"probationExtensionLetter":{"label":"Probation Extension Letter","format":"PE-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"promotionLetter":{"label":"Promotion Letter","format":"PRL-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"incrementLetter":{"label":"Increment Letter","format":"INC-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"transferLetter":{"label":"Transfer Letter","format":"TRL-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"resignationAcceptance":{"label":"Resignation Acceptance Letter","format":"RA-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"terminationLetter":{"label":"Termination Letter","format":"TML-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"warningLetter":{"label":"Warning Letter","format":"WL-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"nda":{"label":"Non-Disclosure Agreement","format":"NDA-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"nonCompeteAgreement":{"label":"Non-Compete Agreement","format":"NCA-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null}}';

-- Backfill: merge the 10 new keys into every existing org's
-- documentNumbering additively — `||` only touches the listed keys, so an
-- org's own edits to its existing 9 entries (or a custom key it added
-- itself) are left untouched. Guarded by NOT (... ? 'confirmationLetter')
-- so re-running this file is a no-op for an org already merged.
UPDATE "organizations"
SET "documentNumbering" = "documentNumbering" || '{"confirmationLetter":{"label":"Confirmation Letter","format":"CL-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"probationExtensionLetter":{"label":"Probation Extension Letter","format":"PE-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"promotionLetter":{"label":"Promotion Letter","format":"PRL-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"incrementLetter":{"label":"Increment Letter","format":"INC-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"transferLetter":{"label":"Transfer Letter","format":"TRL-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"resignationAcceptance":{"label":"Resignation Acceptance Letter","format":"RA-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"terminationLetter":{"label":"Termination Letter","format":"TML-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"warningLetter":{"label":"Warning Letter","format":"WL-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"nda":{"label":"Non-Disclosure Agreement","format":"NDA-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null},"nonCompeteAgreement":{"label":"Non-Compete Agreement","format":"NCA-{DD_MM_YYYY}-{00001}","resetRule":"yearly","counter":0,"lastPeriodKey":null}}'::jsonb
WHERE NOT ("documentNumbering" ? 'confirmationLetter');
